# Generated by Django 4.1.7 on 2023-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_room_roommember"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hash",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
